package prompt.ls1.model.enums;

public enum CoursePhaseType {
    PRE_APPLICATION,
    APPLICATION,
    STUDENT_PRE_SELECTION,
    STUDENT_ADMISSION,
    INTRO_COURSE_PLANNING,
    INTRO_COURSE_ASSESSMENT,
    PROJECT_PREFERENCES_COLLECTION,
    TEAM_ALLOCATION,
    PROJECT_INFRASTRUCTURE_SETUP,
    INTERMEDIATE_GRADING,
    FINAL_DELIVERY,
    FINAL_GRADING,
    OTHER
}
