export enum Query {
  AUTHENTICATION = 'authentication',
  THESIS_APPLICATION = 'thesisApplication',
  THESIS_ADVISOR = 'thesisAdvisor',
  DEVELOPER_APPLICATION = 'developerApplication',
  COACH_APPLICATION = 'coachApplication',
  TUTOR_APPLICATION = 'tutorApplication',
  COURSE_ITERATION = 'courseIteration',
  COURSE_PHASE = 'coursePhase',
  PROJECT_TEAM = 'projectTeam',
  SKILL = 'skill',
  INTRO_COURSE_PARTICIPATIONS = 'introCourseParticipations',
  INTRO_COURSE_TUTORS = 'introCourseTutors',
  POST_KICK_OFF = 'postKickOff',
}
