name: Build Docker Image

on:
  workflow_call:
    outputs:
      server_image_tag: 
        description: "The tag of the server image that was built"
        value: ${{ jobs.build.outputs.server_image_tag }}
      client_image_tag: 
        description: "The tag of the client image that was built"
        value: ${{ jobs.build.outputs.client_image_tag }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./client/Dockerfile
            image: ghcr.io/ls1intum/prompt/prompt-client
            context: ./client
            path: client
          - dockerfile: ./server/Dockerfile
            image: ghcr.io/ls1intum/prompt/prompt-server
            context: ./server
            path: server
    outputs:
      server_image_tag: "${{ steps.output-tag-server.outputs.server_image_tag }}"
      client_image_tag: "${{ steps.output-tag-client.outputs.client_image_tag }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get changed files in the client folder
        id: changed-files-client-folder
        uses: tj-actions/changed-files@v44
        with:
          files: client/**

      - name: Get changed files in the server folder
        id: changed-files-server-folder
        uses: tj-actions/changed-files@v44
        with:
          files: server/**

      - name: Build and push Docker Image
        uses: ls1intum/.github/.github/build-and-push-docker@composite-action
        id: meta
        if: ${{ (steps.changed-files-client-folder.outputs.any_changed == 'true' && matrix.path == 'client') || (steps.changed-files-server-folder.outputs.any_changed == 'true' && matrix.path == 'server') }}
        with:
          docker-context: ${{ matrix.context }}
          docker-file: ${{ matrix.dockerfile }}
          build-args: |
            "SERVER_HOST=${{ vars.SERVER_HOST }}"
            "KEYCLOAK_HOST=${{ vars.KEYCLOAK_HOST }}"
            "KEYCLOAK_REALM_NAME=${{ vars.KEYCLOAK_REALM_NAME }}"

      - id: output-tag-client
        run: |
          if [[ "${{ matrix.path }}" == "client" ]] && [[ "${{ steps.changed-files-client-folder.outputs.any_changed }}" == "true" ]]; then
            echo "client_image_tag=${{ steps.meta.outputs.tags }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.path }}" == "client" ]]; then
            echo "client_image_tag=latest" >> "$GITHUB_OUTPUT"
          fi
      
      - id: output-tag-server
        run: |
          if [[ "${{ matrix.path }}" == "server" ]] && [[ "${{ steps.changed-files-server-folder.outputs.any_changed }}" == "true" ]]; then
            echo "server_image_tag=${{ steps.meta.outputs.tags }}" >> "$GITHUB_OUTPUT"
          elif [[ "${{ matrix.path }}" == "server" ]]; then
            echo "server_image_tag=latest" >> "$GITHUB_OUTPUT"
          fi
